name = "ahp-mod-cloudflare-monitor"
main = "./functions/api/index.js"
compatibility_date = "2023-10-30"

# Route all requests to the public directory by default
[site]
bucket = "./public"

# Define KV namespace for storing monitoring data
[[kv_namespaces]]
binding = "MONITOR_DATA"
id = "monitor-data"
preview_id = "monitor-data-preview"

# Define environment variables
[vars]
MAIN_APP_URL = "https://ahp-mod-2-0-cloud.onrender.com"
RENDER_MONITOR_URL = "https://ahp-mod-2-0-cloud-1.onrender.com"
PING_INTERVAL = "15000"
ALERT_THRESHOLD = "3"

# Define cron triggers for background monitoring
[triggers]
crons = ["*/1 * * * *"] # Run every minute

# Define routes for API endpoints
[[routes]]
pattern = "/api/ping"
script = "./functions/api/ping.js"

[[routes]]
pattern = "/api/status"
script = "./functions/api/status.js"

[[routes]]
pattern = "/api/metrics"
script = "./functions/api/metrics.js"
