# Cloudflare Pages configuration
name = "ahp-mod-cloudflare-monitor"
compatibility_date = "2023-10-30"

# This is the key property for Cloudflare Pages
pages_build_output_dir = "dist"

# Define KV namespace for storing monitoring data
[[kv_namespaces]]
binding = "MONITOR_DATA"
id = "monitor-data"
preview_id = "monitor-data-preview"

# Define environment variables
[vars]
MAIN_APP_URL = "https://ahp-mod-2-0-cloud.onrender.com"
RENDER_MONITOR_URL = "https://ahp-mod-2-0-cloud-1.onrender.com"
PING_INTERVAL = "15000"
ALERT_THRESHOLD = "3"
